language: rust
sudo: false
cache: cargo
rust:
  - nightly
script:
  - cargo check --features=cuda --verbose --all
  - cargo test --verbose --all
notifications:
  slack: parkas-team:0twCBUENCd9xqXn4DEVm0gEX
