---
language: rust
cache: cargo
# kcov currently broken on travis for non-sudo builds § https://github.com/roblabla/cargo-travis/issues/32
sudo: required
rust:
  - nightly
  - stable
addons:
  apt:
    packages:
      # F/lex depedencies (needed by telamon-gen) § https://github.com/ulysseB/telamon/blob/989621f5cf1099fda6ba14b4eda18b1cd9d4660a/telamon-gen/build.rs#L14
      - flex

      # Criterion's dependency Quickstart § https://github.com/japaric/criterion.rs#quickstart
      - gnuplot

      # Kcov's Installing dependencies § https://github.com/SimonKagstrom/kcov/blob/master/INSTALL.md#ubuntu
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev

before_script:
  - flex --version

script:
  - |
    if [ $TRAVIS_RUST_VERSION == "nightly" ];
      then
        cargo test --no-run --all
        cargo doc --no-deps --all
      else
        cargo test --all
        cargo doc --all
    fi
     

after_success:
  # Kcov's Building § https://github.com/SimonKagstrom/kcov/blob/master/INSTALL.md#building
  - git clone https://github.com/SimonKagstrom/kcov.git
  - mkdir kcov/build
  - cd kcov/build
  - cmake ..
  - make
  - make install DESTDIR=../..
  - cd -

  - |
    for file in target/debug/telamon*[^\.d];
      do
        mkdir -p "target/cov/$(basename $file)";

        # Kcov's Travis-ci / coveralls integration § https://github.com/SimonKagstrom/kcov/blob/master/doc/coveralls.md#travis-ci--coveralls-integration
        ./usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file";
    done

  - mv target/cov target/doc

  # Criterion's run Quickstart § https://github.com/japaric/criterion.rs#quickstart
  - |
    if [ $TRAVIS_RUST_VERSION == "nightly" ];
      then
        cd telamon-gen
        cargo bench
        cd -
        mv telamon-gen/target/criterion target/doc
    fi

deploy:
  - provider: pages
    local-dir: target/doc
    target-branch: gh-pages
    skip-cleanup: true
    keep-history: false
    github-token: "$GITHUB_TOKEN"
    on:
      condition: $TRAVIS_RUST_VERSION = nightly

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
    - secure: T7ao3Xly60lrporBe0RChgoqLAQ8OGegUHYmQ6ZQJJqRwKansrJkd0S4w6ZtLYMqzwX03ycI+B9euPY0km3uSxysssBNJamqLyw2my9+zIOR31+6rP/+MeH1/GPcvJF5foGZAoLwxxIp+wF/5FvsqhgpfoIT1GHDylMKFGuq9lleWc1i03xAV341avjRMi9O23fEpAHEixlXl0rIGl1k6PeUy0nP0bktxk+0Z1pFdi89w3EfCSE5GESWQhylB+vI2CHFDj7rTAMRO1J5KYEcXjpKGPpdYdmJz7Egp3qimIzdNUiIJxEJOdXUtys2thuf/R8r/neGiP757OX/MDJ0DT7sxqmKeF85BTc8X2KjPgRcjOsSXL5xEmkgRm9UaR2qiBrvpCxCM0EIoIUADMwDbMUCpNzWrPGFCL6SxR8zDc9/aSUWr2Mt41MX7oNWxViQLQACIuh5xnved8c01gsseBCUkyMXybisiZtNts/AolBS5Ayu/qAp0ocZn9xKy7pCxSmLNfl7EVozEjDI8qegv23apqdseGNv2QtR5vM7t4SYsNnBsQosoC5DIICy7BiX0fboKP1qKHFMhJGekka3ky9/wCHbaZb205PLZ9GxEkHVfuOxsFOdszglGZtknvKqdwnxt04gqs33iL6o/1GGOcRiEdvOqhWWrbz+nMUQqV8=
