condense_wildcard_suffixes = true
format_strings = true
fn_single_line = true
max_width = 90
comment_width = 90
reorder_imported_names = true
reorder_imports = true
reorder_extern_crates = true
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true

ignore = [
  "telamon-gen/src/print/template",
]
